apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: blog
  name: blog
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: blog
    spec:
      containers:
      - image: diptochakrabarty/blog:v3
        name: blog
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
