version: "3"
services: 
    blog:
      container_name: blog
      restart: always
      image: blog:v2
      ports:
        - "3000:3000"
    mongo:
      container_name: mongo
      image: mongo
      volumes:
        - .:/data/db
      ports:
        - "27017:27017"