version: "3"
services: 
  mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./db:/data/db
      ports:
        - "27020:27017"
  blog:
      container_name: blog
      restart: always
      image: diptochakrabarty/blog:v5
      links:
        - mongo
      ports:
        - "3000:3000"
     
    
